<?php

namespace AppBundle\Repository;

/**
 * BachelorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BachelorRepository extends \Doctrine\ORM\EntityRepository
{

}
